- name: upgrade packages
  yum:
    name: '*'
    state: latest
- name: git install
  yum:
    name: git
    state: latest
- name: config host lab ansible
  lineinfile: 
    dest: /etc/hosts 
    state: present
    line: "{{item}}"
  with_items: 
  - 192.168.1.2 control-node
  - 192.168.1.3 app01
  - 192.168.1.4 db01