Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: "echo Condig docker swam cluster"

    config.vm.define "manager" do |manager|
        manager.vm.box = "centos/7"
        manager.vm.hostname = "manager"
        manager.vm.provision "shell", path: "provision.sh"
        manager.vm.network "private_network", ip: "192.168.1.2"
        manager.vm.network "forwarded_port", guest: 80, host: 8080
    end

    config.vm.define "worker1" do |manager|
        manager.vm.box = "centos/7"
        manager.vm.hostname = "worker1"
        manager.vm.provision "shell", path: "provision.sh"
        manager.vm.network "private_network", ip: "192.168.1.3"
    end

    config.vm.define "worker2" do |manager|
        manager.vm.box = "centos/7"
        manager.vm.hostname = "manager"
        manager.vm.provision "shell", path: "provision.sh"
        manager.vm.network "private_network", ip: "192.168.1.4"
    end

end    